export const departmentOptions = [
  "Accident and Emergency",
  "Admissions",
  "Anesthetics",
  "Breast Screening",
  "Burn Center/Unit",
  "Cardiology",
  "Central Sterile Services",
  "Chaplaincy",
  "Coronary Care Unit",
  "Critical/Intensive Care",
  "Diagnostic Imaging",
  "Discharge",
  "Elderly Services",
  "Finance",
  "Gastroenterology",
  "General Services",
  "General Surgery",
  "Gynecology",
  "Hematology",
  "Health & Safety",
  "Hospitalist",
  "Human Resources",
  "Infection Control",
  "Information Management",
  "Maternity",
  "Medical Records",
  "Microbiology",
  "Neonatal",
  "Nephrology",
  "Neurology",
  "Nutrition and Dietetics",
  "Obstetrics",
  "Occupational Therapy",
  "Oncology",
  "Ophthalmology",
  "Orthopedics",
  "Otolaryngology",
  "Pain Management",
  "Patient Services",
  "Pharmacy",
  "Physiotherapy",
  "Purchasing & Supplies",
  "Radiology",
  "Radiotherapy",
  "Renal",
  "Rheumatology",
  "Sexual Health",
  "Social Work",
  "Urology",
];
